services:
  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000"
    environment:
      - CORS_ORIGIN=http://localhost:5173  # Placeholder, will be replaced dynamically
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge